DB연결 및 엔티티 생성
Pray2U/Pray2U_Homepage_BE pull request #3
Opened 2023-06-27 12:36 UTC by Dongbok-Lee

데이터 베이스 연결 및 엔티티 생성
-properties 값은 노션 참조
-전체적으로 확인 후 코드 리뷰 후 병합

2023-06-30 16:30 UTC, limjongheok requested changes

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/board/entity/Board.java
> +    @Column(name = "product_id")
왜 board_id 가 아닌 product_id 인지??

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +public class Item extends BaseTimeEntity {
ERD에 는 TABLE 명 SALE_ITEM 밖에 없음 table(name ="") 이나 클래스 name 수정 요망

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/memberapproval/entity/MemberApproval.java
> +@Getter
erd에는 REGISTRATION_APPROVAL 로 되어 있음 TABLE NAME 수정 요망

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +    public Item(long id, String itemName, String imgUrl, long point, String itemDescription) {
생성자가 4개 이상부터는 Builder 패턴이 아닌지?

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/order/entity/Order.java
> +    public Order(User user, Item item, LocalDateTime useDate, boolean useStatus, String targetUser) {
생성자가 4개 이상부터는 Builder 패턴이 아닌지?

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/rank/entity/Rank.java
> +    public Rank(long weekPoint, LocalDateTime startDate, LocalDateTime endDate, int ranking) {
생성자가 4개 이상부터는 Builder 패턴이 아닌지?

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/til/entity/Til.java
> +    public Til(User user, String title, String tag, String content, boolean deleted) {
생성자가 4개 이상부터는 Builder 패턴이 아닌지?

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/user/entity/User.java
> +    private String username;
userName

2023-06-30 16:30 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/memberapproval/entity/MemberApproval.java
> +    private String username;
userName 으로 수정 itemName 은  itemName으로 되어 있으니 일관성 유지

2023-07-02 07:36 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/memberapproval/entity/MemberApproval.java
> +    private String username;
username은 보통 한 단어로 취급하기 때문에 보통은 카멜케이스 적용을 안한다고 함.

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/til/entity/Til.java
> +    public Til(User user, String title, String tag, String content, boolean deleted) {
수정완료

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/rank/entity/Rank.java
> +    public Rank(long weekPoint, LocalDateTime startDate, LocalDateTime endDate, int ranking) {
수정완료

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/order/entity/Order.java
> +    public Order(User user, Item item, LocalDateTime useDate, boolean useStatus, String targetUser) {
수정완료

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +    public Item(long id, String itemName, String imgUrl, long point, String itemDescription) {
수정완료

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/memberapproval/entity/MemberApproval.java
> +@Getter
ERD변경예정

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +public class Item extends BaseTimeEntity {
ERD변경예정

2023-07-02 07:37 UTC, Dongbok-Lee commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/board/entity/Board.java
> +    @Column(name = "product_id")
수정완료

2023-07-02 11:07 UTC, limjongheok commented
확인 완료

2023-07-02 11:09 UTC, limjongheok approved these changes
변경 확인 완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/board/entity/Board.java
> +    @Column(name = "product_id")
확인 완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +public class Item extends BaseTimeEntity {
확인완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/item/entity/Item.java
> +    public Item(long id, String itemName, String imgUrl, long point, String itemDescription) {
확인완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/memberapproval/entity/MemberApproval.java
> +@Getter
확인완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/order/entity/Order.java
> +    public Order(User user, Item item, LocalDateTime useDate, boolean useStatus, String targetUser) {
확인완료

2023-07-02 11:09 UTC, limjongheok commented on p2uhomepage/src/main/java/com/pray2you/p2uhomepage/domain/rank/entity/Rank.java
> +    public Rank(long weekPoint, LocalDateTime startDate, LocalDateTime endDate, int ranking) {
확인완료

2023-07-02 12:54 UTC, merged